Repository HIM-Health-Indoor-Machine/him-backend, pull requests merged in 2024-11, with the labels that each got.

#32 오늘의 챌린지 생성 및 조회 기능 추가
  src/main/java/com/him/fpjt/him_backend/exercise/controller/TodayChallengeController.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/ChallengeDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/TodayChallengeDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/domain/TodayChallenge.java
  src/main/java/com/him/fpjt/him_backend/exercise/dto/TodayChallengeDto.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImpl.java
  src/main/resources/mappers/ChallengeMapper.xml
  src/main/resources/mappers/TodayChallengeMapper.xml
  src/test/java/com/him/fpjt/him_backend/exercise/service/ChallegeServiceImplTest.java
  src/test/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImplTest.java
Labels: feat

#26 feat : dao
  src/main/java/com/him/fpjt/him_backend/HimBackendApplication.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/GameDao.java
  src/main/java/com/him/fpjt/him_backend/user/dao/UserDao.java
  src/main/resources/mappers/GameMapper.xml
  src/main/resources/mappers/UserMapper.xml
Labels: feat

#30 feat : dto 수정
  src/main/java/com/him/fpjt/him_backend/exercise/domain/Game.java
  src/main/java/com/him/fpjt/him_backend/user/domain/User.java
Labels: documentation

#33 게임 기능
  src/main/java/com/him/fpjt/him_backend/HimBackendApplication.java
  src/main/java/com/him/fpjt/him_backend/common/constants/ExpPoints.java
  src/main/java/com/him/fpjt/him_backend/exercise/controller/GameController.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/GameDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/domain/Game.java
  src/main/java/com/him/fpjt/him_backend/exercise/dto/GameDto.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/GameService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/GameServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/user/dao/UserDao.java
  src/main/java/com/him/fpjt/him_backend/user/service/UserService.java
  src/main/java/com/him/fpjt/him_backend/user/service/UserServiceImpl.java
  src/main/resources/mappers/GameMapper.xml
  src/test/java/com/him/fpjt/him_backend/exercise/service/GameServiceImplTest.java
  src/test/java/com/him/fpjt/him_backend/user/service/UserServiceImplTest.java
Labels: feat

#34 챌린지 운동 결과 업데이트 및 경험치 반영
  build.gradle
  src/main/java/com/him/fpjt/him_backend/HimBackendApplication.java
  src/main/java/com/him/fpjt/him_backend/common/constants/ExpPoints.java
  src/main/java/com/him/fpjt/him_backend/exercise/controller/TodayChallengeController.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/ChallengeDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/TodayChallengeDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/dto/TodayChallengeDto.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImpl.java
  src/main/resources/mappers/ChallengeMapper.xml
  src/main/resources/mappers/TodayChallengeMapper.xml
  src/test/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImplTest.java
Labels: feat

#36 출석 여부에 따른 경험치 반영
  src/main/java/com/him/fpjt/him_backend/common/constants/ExpPoints.java
  src/main/java/com/him/fpjt/him_backend/user/controller/AttendanceController.java
  src/main/java/com/him/fpjt/him_backend/user/dao/AttendanceDao.java
  src/main/java/com/him/fpjt/him_backend/user/dao/UserDao.java
  src/main/java/com/him/fpjt/him_backend/user/domain/Attendance.java
  src/main/java/com/him/fpjt/him_backend/user/service/AttendanceServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/user/service/AttendenceService.java
  src/main/java/com/him/fpjt/him_backend/user/service/UserService.java
  src/main/java/com/him/fpjt/him_backend/user/service/UserServiceImpl.java
  src/main/resources/mappers/AttendanceMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/test/java/com/him/fpjt/him_backend/exercise/service/AttendanceServiceImplTest.java
Labels: feat

#37 일관된 todaychallenge 데이터 처리를 위한 todayChallenge 생성 코드 수정
  src/main/java/com/him/fpjt/him_backend/exercise/controller/TodayChallengeController.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/ChallengeDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/TodayChallengeDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImpl.java
  src/main/resources/mappers/ChallengeMapper.xml
  src/main/resources/mappers/TodayChallengeMapper.xml
  src/test/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImplTest.java
Labels: feat

#40 챌린지 수정 및 오늘 날짜 챌린지 상태 변경 기능 추가
  src/main/java/com/him/fpjt/him_backend/exercise/controller/ChallengeController.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/ChallengeDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/domain/Challenge.java
  src/main/java/com/him/fpjt/him_backend/exercise/dto/ChallengeDto.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeServiceImpl.java
  src/main/resources/mappers/ChallengeMapper.xml
  src/test/java/com/him/fpjt/him_backend/exercise/service/ChallegeServiceImplTest.java
Labels: feat

#41 refactor : 필요없는 메서드 삭제
  src/main/java/com/him/fpjt/him_backend/exercise/dao/ChallengeDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeService.java
  src/main/resources/mappers/ChallengeMapper.xml
Labels: refactor

#42 refactor : 누락된 메서드 추가
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeServiceImpl.java
Labels: refactor

#44 사용자 정보 조회 및 수정 기능 추가
  src/main/java/com/him/fpjt/him_backend/user/controller/UserController.java
  src/main/java/com/him/fpjt/him_backend/user/dao/UserDao.java
  src/main/java/com/him/fpjt/him_backend/user/domain/User.java
  src/main/java/com/him/fpjt/him_backend/user/dto/UserInfoDto.java
  src/main/java/com/him/fpjt/him_backend/user/dto/UserModifyDto.java
  src/main/java/com/him/fpjt/him_backend/user/service/UserService.java
  src/main/java/com/him/fpjt/him_backend/user/service/UserServiceImpl.java
  src/main/resources/HIM_schema.sql
  src/main/resources/mappers/UserMapper.xml
  src/test/java/com/him/fpjt/him_backend/user/service/UserServiceImplTest.java
Labels: feat

#45 닉네임 중복 여부 확인 기능 추가
  src/main/java/com/him/fpjt/him_backend/user/controller/AuthController.java
  src/main/java/com/him/fpjt/him_backend/user/dao/UserDao.java
  src/main/java/com/him/fpjt/him_backend/user/service/AuthService.java
  src/main/java/com/him/fpjt/him_backend/user/service/AuthServiceImpl.java
  src/main/resources/mappers/UserMapper.xml
  src/test/java/com/him/fpjt/him_backend/exercise/service/AuthServiceImplTest.java
Labels: feat

#46 이메일 인증번호 발송 및 인증번호 확인, 만료된 인증번호 삭제 기능 추가
  build.gradle
  src/main/java/com/him/fpjt/him_backend/HimBackendApplication.java
  src/main/java/com/him/fpjt/him_backend/auth/controller/AuthController.java
  src/main/java/com/him/fpjt/him_backend/auth/dao/VerificationCodeDao.java
  src/main/java/com/him/fpjt/him_backend/auth/domain/VerificationCode.java
  src/main/java/com/him/fpjt/him_backend/auth/dto/VerificationCodeDto.java
  src/main/java/com/him/fpjt/him_backend/auth/service/AuthService.java
  src/main/java/com/him/fpjt/him_backend/auth/service/AuthServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/common/constants/EmailTemplates.java
  src/main/java/com/him/fpjt/him_backend/common/util/CodeGenerator.java
  src/main/java/com/him/fpjt/him_backend/common/util/EmailSender.java
  src/main/java/com/him/fpjt/him_backend/user/controller/AuthController.java
  src/main/java/com/him/fpjt/him_backend/user/dao/UserDao.java
  src/main/java/com/him/fpjt/him_backend/user/service/AuthService.java
  src/main/java/com/him/fpjt/him_backend/user/service/AuthServiceImpl.java
  src/main/resources/HIM_schema.sql
  src/main/resources/application.yml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/mappers/VerificationCodeMapper.xml
  src/test/java/com/him/fpjt/him_backend/exercise/service/AuthServiceImplTest.java
Labels: feat

#48 에러 공통 처리 모듈 적용
  src/main/java/com/him/fpjt/him_backend/auth/controller/AuthController.java
  src/main/java/com/him/fpjt/him_backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/him/fpjt/him_backend/common/exception/dto/ExceptionDto.java
  src/main/java/com/him/fpjt/him_backend/exercise/controller/ChallengeController.java
  src/main/java/com/him/fpjt/him_backend/exercise/controller/GameController.java
  src/main/java/com/him/fpjt/him_backend/exercise/controller/TodayChallengeController.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/GameService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/GameServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/user/controller/AttendanceController.java
  src/main/java/com/him/fpjt/him_backend/user/controller/UserController.java
  src/main/java/com/him/fpjt/him_backend/user/service/AttendanceServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/user/service/AttendenceService.java
  src/main/java/com/him/fpjt/him_backend/user/service/UserService.java
  src/main/java/com/him/fpjt/him_backend/user/service/UserServiceImpl.java
Labels: refactor

#49 fix : tier 종류 변경
  src/main/java/com/him/fpjt/him_backend/user/domain/Tier.java
Labels: fix

#51 게임 : FE BE api 연동
  src/main/java/com/him/fpjt/him_backend/exercise/controller/GameController.java
  src/main/java/com/him/fpjt/him_backend/exercise/domain/Game.java
  src/main/java/com/him/fpjt/him_backend/exercise/dto/GameDto.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/GameService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/GameServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mappers/GameMapper.xml
Labels: feat

#52 challenge 필드 수정 및 생성자 추가
  src/main/java/com/him/fpjt/him_backend/exercise/controller/ChallengeController.java
  src/main/java/com/him/fpjt/him_backend/exercise/domain/Challenge.java
  src/main/java/com/him/fpjt/him_backend/exercise/domain/TodayChallenge.java
  src/main/java/com/him/fpjt/him_backend/exercise/dto/ChallengeDto.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeServiceImpl.java
  src/main/resources/HIM_schema.sql
  src/main/resources/mappers/ChallengeMapper.xml
  src/main/resources/mappers/TodayChallengeMapper.xml
  src/test/java/com/him/fpjt/him_backend/exercise/service/ChallegeServiceImplTest.java
  src/test/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImplTest.java
Labels: fix

#53 todayChallenge CORS 추가 및 조회 파라미터 변경
  src/main/java/com/him/fpjt/him_backend/exercise/controller/TodayChallengeController.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/TodayChallengeDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImpl.java
  src/main/resources/HIM_schema.sql
  src/main/resources/mappers/TodayChallengeMapper.xml
Labels: feat

#55 user와 todayChallenge, game 연동에 따른 game, todayChallenge 조회 API 추가
  src/main/java/com/him/fpjt/him_backend/exercise/controller/GameController.java
  src/main/java/com/him/fpjt/him_backend/exercise/controller/TodayChallengeController.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/GameDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/TodayChallengeDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/domain/TodayChallenge.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/GameService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/GameServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/user/controller/AttendanceController.java
  src/main/java/com/him/fpjt/him_backend/user/controller/UserController.java
  src/main/resources/HIM_schema.sql
  src/main/resources/mappers/ChallengeMapper.xml
  src/main/resources/mappers/GameMapper.xml
  src/main/resources/mappers/TodayChallengeMapper.xml
  src/test/java/com/him/fpjt/him_backend/exercise/service/ChallegeServiceImplTest.java
  src/test/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImplTest.java
Labels: feat

#56 fix : transactional 어노테이션 추가
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeServiceImpl.java
Labels: fix

#57 GitHub Actions와 AWS CodeDeploy를 활용한 CI/CD 파이프라인 구축
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .gitignore
  appspec.yml
  scripts/start.sh
  scripts/stop.sh
  src/main/resources/application.yml
Labels: infra

#59 refactor : 프로젝트 banner 변경
  src/main/resources/banner.txt
Labels: fix

#58 Tier 업데이트 로직 추가
  src/main/java/com/him/fpjt/him_backend/user/dao/UserDao.java
  src/main/java/com/him/fpjt/him_backend/user/service/UserServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/user/util/TierManager.java
  src/main/resources/mappers/UserMapper.xml
Labels: fix

#64 인증 / 인가 처리 로직 에러 해결
  src/main/java/com/him/fpjt/him_backend/auth/service/AuthServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/common/config/CorsConfig.java
  src/main/java/com/him/fpjt/him_backend/common/config/SecurityConfig.java
  src/main/java/com/him/fpjt/him_backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/him/fpjt/him_backend/common/filter/JwtRequestFilter.java
  src/main/java/com/him/fpjt/him_backend/common/util/JwtUtil.java
  src/main/resources/mappers/RefreshTokenMapper.xml
Labels: bug

#65 테스트 코드 수정
  src/main/java/com/him/fpjt/him_backend/auth/dto/AuthenticationResponse.java
  src/main/java/com/him/fpjt/him_backend/user/controller/AttendanceController.java
  src/main/java/com/him/fpjt/him_backend/user/controller/UserController.java
  src/test/java/com/him/fpjt/him_backend/auth/JwtRequestFilterTest.java
  src/test/java/com/him/fpjt/him_backend/auth/service/AuthServiceImplTest.java
  src/test/java/com/him/fpjt/him_backend/auth/service/UserDetailsServiceImplTest.java
  src/test/java/com/him/fpjt/him_backend/user/service/UserServiceImplTest.java
Labels: fix

#66 workflow 환경변수 추가
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: infra

#68 챌린지 생성 및 챌린지 경험치 업데이트 로직 수정
  src/main/java/com/him/fpjt/him_backend/exercise/controller/TodayChallengeController.java
  src/main/java/com/him/fpjt/him_backend/exercise/dao/ChallengeDao.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeServiceImpl.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImpl.java
  src/main/resources/mappers/ChallengeMapper.xml
Labels: fix

#67 refactor : 필요 없는 조회 명령어 삭제
  .github/workflows/build.yml
Labels: infra

#69 fix : 챌린지 생성 시 challengeId 반환하도록 로직 수정
  src/main/java/com/him/fpjt/him_backend/exercise/controller/ChallengeController.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeService.java
  src/main/java/com/him/fpjt/him_backend/exercise/service/ChallengeServiceImpl.java
Labels: fix

#70 회원 가입 시 출석 데이터 생성 로직 추가
  src/main/java/com/him/fpjt/him_backend/auth/service/AuthServiceImpl.java
  src/test/java/com/him/fpjt/him_backend/auth/service/AuthServiceImplTest.java
Labels: fix

#71 챌린지 성공 시 출석 상태 변경
  src/main/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImpl.java
  src/test/java/com/him/fpjt/him_backend/exercise/service/ChallegeServiceImplTest.java
  src/test/java/com/him/fpjt/him_backend/exercise/service/TodayChallengeServiceImplTest.java
Labels: fix

#73 fix : cors 설정을 위한 프론트 url 추가
  src/main/java/com/him/fpjt/him_backend/common/config/CorsConfig.java
Labels: fix

#74 프론트엔드 서버 ip url에 대한 cors 설정 추가
  src/main/java/com/him/fpjt/him_backend/common/config/CorsConfig.java
Labels: fix

#75 fix : profile 이미지 url 변경
  src/main/java/com/him/fpjt/him_backend/user/domain/User.java
Labels: fix

#76 profile 이미지 url 변경
  src/main/java/com/him/fpjt/him_backend/user/domain/User.java
Labels: fix

#77 Readme 추가
  README.md
Labels: documentation

#78 fix : 폭탄테마 url 변경
  README.md
Labels: fix
